export default  [ 

{"id" : 1,
"name": "NEODENT OFICIAL",
"url": "https://www.youtube.com/user/NeodentOficial",
"detail": "Canal Oficial",
"ctgy" : "Implantes-Dentales",
"logo": "/images/logos/youtubechannel-img-Neodent.jpg",
"idioma": "Portugués",
},

{"id" : 2,
"name": "STRAUMANN GLOBAL",
"url": "https://www.youtube.com/user/StraumannGlobal",
"detail": "Canal oficial",
"ctgy" : "Implantes-Dentales",
"logo": "/images/logos/youtubechannel-img-Straumann.jpg",
"idioma": "Inglés",
},

{"id" : 3,
"name": "I + D 24x7x365 Inteligencia Dental",
"url": "https://www.youtube.com/user/ID24x7x365",
"detail": "Conferencias gratuitas online",
"ctgy" : "Odontologia-general",
"logo": "/images/logos/youtubechannel-img-id365.jpg",
"idioma": "Español",
},

{"id" : 4,
"name": "I + D Inteligencia Dental",
"url": "https://www.youtube.com/channel/UCIPLNF6_yHnGyuerPPhty8w",
"detail": "Conferencias gratuitas online",
"ctgy" : "general",
"logo": "/images/logos/youtubechannel-img-id.jpg",
"idioma": "Español",
},

{"id" : 5,
"name": "Coltene Latinoamerica",
"url": "https://www.youtube.com/user/coltenelatinoamerica",
"detail": "Canal Oficial",
"ctgy" : "Odontologia-general",
"logo": "/images/logos/youtubechannel-img-coltene.jpg",
"idioma": "Español",
},
]