export default  [ 

{"id" : 1,
"name": "NEODENT OFICIAL",
"url": "https://www.youtube.com/user/NeodentOficial",
"detail": "Canal Oficial",
"ctgy" : "Implantes-Dentales",
"logo": "/images/logos/youtubechannel-img-Neodent.jpg",
"idioma": "Portugués",
},

{"id" : 2,
"name": "STRAUMANN GLOBAL",
"url": "https://www.youtube.com/user/StraumannGlobal",
"detail": "Canal oficial",
"ctgy" : "Implantes-Dentales",
"logo": "/images/logos/youtubechannel-img-Straumann.jpg",
"idioma": "Inglés",
},

{"id" : 3,
"name": "I + D 24x7x365 ",
"url": "https://www.youtube.com/user/ID24x7x365",
"detail": "Conferencias gratuitas online",
"ctgy" : "Odontologia-general",
"logo": "/images/logos/youtubechannel-img-id365.jpg",
"idioma": "Español",
},

{"id" : 4,
"name": "I + D Inteligencia Dental",
"url": "https://www.youtube.com/channel/UCIPLNF6_yHnGyuerPPhty8w",
"detail": "Conferencias gratuitas online",
"ctgy" : "general",
"logo": "/images/logos/youtubechannel-img-id.jpg",
"idioma": "Español",
},

{"id" : 5,
"name": "Coltene Latinoamerica",
"url": "https://www.youtube.com/user/coltenelatinoamerica",
"detail": "Canal Oficial",
"ctgy" : "Odontologia-general",
"logo": "/images/logos/youtubechannel-img-coltene.jpg",
"idioma": "Español",
},
{"id" : 6,
"name": "3M Oral Care",
"url": "https://www.youtube.com/user/coltenelatinoamerica",
"detail": "Canal Oficial",
"ctgy" : "Odontologia-general",
"logo": "/images/logos/youtubechannel-img-3mOralCare.jpg",
"idioma": "Inglés",
},
{"id" : 7,
"name": "American Orthodontics",
"url": "https://www.youtube.com/user/AmericanOrthodontics",
"detail": "Canal Oficial",
"ctgy" : "Ortodoncia",
"logo": "/images/logos/youtubechannel-img-AOrthodontics.jpg",
"idioma": "Inglés",
},
{"id" : 8,
"name": "Forestadent Colombia",
"url": "https://www.youtube.com/channel/UCWPL_ZlMg7vVtsH0BEyVB7w",
"detail": "Videos relacionados con Escaner 3D",
"ctgy" : "Odontologia-Digital",
"logo": "/images/logos/youtubechannel-img-forestadentCol.jpg",
"idioma": "Español",
},
{"id" : 9,
"name": "Style Italiano",
"url": "https://www.youtube.com/user/StyleItaliano2010",
"detail": "Canal del grupo Style Italiano de Operatoria Dental",
"ctgy" : "Operatoria-Dental-Estética",
"logo": "/images/logos/youtubechannel-img-StyleItaliano.jpg",
"idioma": "Inglés",
},
{"id" : 10,
"name": "Oral B LATAM",
"url": "https://www.youtube.com/channel/UCs_s-qFp8RdMZ8Cw4nmPdQw",
"detail": "Canal Oficial",
"ctgy" : "Odontologia-General",
"logo": "/images/logos/youtubechannel-img-OralBLatam.jpg",
"idioma": "Inglés",
},
]